<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-T5IOI3H" ignored="0" name="Test" tests="2" failures="2" timestamp="2022-07-05T00:20:05 CEST" time="316.282" errors="0">
  <testcase name="VerifyValidLogin" time="40.502" classname="docker.ValidLogin">
    <failure type="java.lang.AssertionError" message="expected [https://wave-trial.getbynder.com/account/dashboard/] but found [https://wave-trial.getbynder.com/verify/]">
      <![CDATA[java.lang.AssertionError: expected [https://wave-trial.getbynder.com/account/dashboard/] but found [https://wave-trial.getbynder.com/verify/]
at docker.ValidLogin.VerifyValidLogin(ValidLogin.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- VerifyValidLogin -->
  <testcase name="VerifyInvalidValidLogin" time="35.015" classname="docker.InvalidLogin">
    <failure type="java.lang.AssertionError" message="Webpage to enter captcha is displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Webpage to enter captcha is displayed expected [true] but found [false]
at docker.InvalidLogin.VerifyInvalidValidLogin(InvalidLogin.java:55)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- VerifyInvalidValidLogin -->
</testsuite> <!-- Test -->
